### ISSUE TITLE
Error: MissingPluginException

### ISSUE THREAD

**Issue by KwekuYamoah** [ably/ably-flutter#101]
I am integrating Ably with a flutter app I am building to be able to do live data streaming. Anytime I debug using Microsoft edge or google chrome browser I get this error;

Error: MissingPluginException(No implementation found for method registerAbly on channel io.ably.flutter.plugin)
    at Object.throw_ [as throw] (http://localhost:52520/dart_sdk.js:5344:11)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:52520/packages/flutter/src/services/system_channels.dart.lib.js:962:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:52520/dart_sdk.js:39201:33
    at _RootZone.runUnary (http://localhost:52520/dart_sdk.js:39058:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:52520/dart_sdk.js:34044:29)
    at handleValueCallback (http://localhost:52520/dart_sdk.js:34604:49)
    at Function._propagateToListeners (http://localhost:52520/dart_sdk.js:34642:17)
    at _Future.new.[_completeWithValue] (http://localhost:52520/dart_sdk.js:34484:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:52520/dart_sdk.js:34507:35)
    at Object._microtaskLoop (http://localhost:52520/dart_sdk.js:39345:13)
    at _startMicrotaskLoop (http://localhost:52520/dart_sdk.js:39351:13)
    at http://localhost:52520/dart_sdk.js:34858:9

**Comment by QuintinWillison** [comment]
Hello @KwekuYamoah and sorry for the delay in response. Thanks for reporting this!

We've not yet planned when we might add web support, or even a native Dart package, so I can't solve this for you right now unfortunately. Please see @kavalerov's response on #95. 😁
