### ISSUE TITLE
Error with onDeactivate 

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-flutter#294]
Customers reporting an error with customers not receiving realtime messages through push. This happened after we had some issues with delivering push notifications in realtime platform.

More info provided by customers
```

Exception: [AblyOfficialPlugin] Push Notification onDeactivate due to ErrorInfo message=Token deviceId does not match requested device operation code=null statusCode=401 href=null

["#0 LoggerUtil.error (package:module_logger/logger.dart:27)","#1 LoggerUtil.e (package:module_logger/logger.dart:23)","#2 AblyOfficialPlugin._setUpEventHandlers._logIfErrorExist (package:digital_banking_app/common/ably/plugin/ably_official_plugin.dart:475)","#3 AblyOfficialPlugin._setUpEventHandlers.<anonymous closure> (package:digital_banking_app/common/ably/plugin/ably_official_plugin.dart:486)","#4 AblyOfficialPlugin._setUpEventHandlers.<anonymous closure> (package:digital_banking_app/common/ably/plugin/ably_official_plugin.dart:485)","#5 _rootRunUnary (dart:async/zone.dart:1362)","#6 _CustomZone.runUnary (dart:async/zone.dart:1265)","#7 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170)","#8 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)","#9 _DelayedData.perform (dart:async/stream_impl.dart:591)","#10 _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)","#11 _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663)","#12 _rootRun (dart:async/zone.dart:1346)","#13 _CustomZone.run (dart:async/zone.dart:1258)","#14 _CustomZone.runGuarded (dart:async/zone.dart:1162)","#15 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202)","#16 _rootRun (dart:async/zone.dart:1354)","#17 _CustomZone.run (dart:async/zone.dart:1258)","#18 _CustomZone.runGuarded (dart:async/zone.dart:1162)","#19 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202)","#20 _microtaskLoop (dart:async/schedule_microtask.dart:40)","#21 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)",""]
```

**Comment by ikbalkaya** [comment]
Check line 269  `PushActivationState` on ably-cocoa where this error was created.

**Comment by ikbalkaya** [comment]
This is related to https://github.com/ably/ably-cocoa/issues/1263

**Comment by ikurek** [comment]
This seems to be blocked until https://github.com/ably/docs/issues/1288 gets resolved
