### ISSUE TITLE
install via pub.dev ?

### ISSUE THREAD

**Issue by SogoGolf** [ably/ably-flutter#40]
hi all, we're very keen to use Ably in our Flutter app. are you able to put this package onto pub.dev ? if not can you give me info on how to install into an existing Flutter app ?

**Comment by zoechi** [comment]
You can add Git repositories to you application
https://dart.dev/tools/pub/dependencies#git-packages
Be aware that this package is still under development.

**Comment by zoechi** [comment]
I'm going to close. Feel free to comment anyway if you need further guidance.

**Comment by SogoGolf** [comment]
I see your in Austria! Our favourite country. Been to Stubai glacier 4 times so far, love it there.

**Comment by SogoGolf** [comment]
i tried the following in an empty/new Flutter project:

```
dependencies:
  flutter:
    sdk: flutter
  ably_flutter_plugin:
    git: https://github.com/ably/ably-flutter.git
```

however the app would not build. is the above incorrect ?

i might just be a bit too early to the party for Ably on Flutter. is there an eta for making it available via pub.dev ?

```
Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build done.                                           14.2s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-09-11 21:19:52.763 xcodebuild[16243:8585479] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2020-09-11 21:19:52.764 xcodebuild[16243:8585479] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2020-09-11 21:19:52.764 xcodebuild[16243:8585479] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdjustFontSize.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    ** BUILD FAILED **
Xcode's output:
↳
   .......
```

**Comment by QuintinWillison** [comment]
@SogoGolf we're hoping to get a first version published before the end of the year, hopefully sooner. Thanks for bearing with us.

In the meantime, I'll give this a quick go myself and see what I get...

**Comment by QuintinWillison** [comment]
I get a different result, but it doesn't build. I see:

```
% flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                              1.8s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `ably_flutter_plugin` from `.symlinks/plugins/ably_flutter_plugin/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "ably_flutter_plugin":
      In Podfile:
        ably_flutter_plugin (from `.symlinks/plugins/ably_flutter_plugin/ios`)

    Specs satisfying the `ably_flutter_plugin (from `.symlinks/plugins/ably_flutter_plugin/ios`)` dependency were found, but they required a higher minimum deployment target.

    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
    /Users/quintin/.asdf/installs/ruby/2.7.0/bin/pod:23:in `load'
    /Users/quintin/.asdf/installs/ruby/2.7.0/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
    /Users/quintin/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/cdn_source.rb:342: warning: URI.escape is obsolete

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro Max.
```

for information:

```
% xcodebuild -version
Xcode 11.3.1
Build version 11C505

% pod --version
1.9.3

% flutter --version
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (10 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

I think we'll need to look at this further as it'll likely be something we'll also need to fix for publish via pub.dev.

**Comment by SogoGolf** [comment]
hey folks - big thanks for the updates and putting the package on pub.dev. we just tested here again (use case being real time leaderboards on mobile) and the latest version (ably_flutter_plugin: ^1.0.0+dev.2) worked like a charm! we're actually using 2 x Ably API's (Azure Cosmosdb real time change feed -> Ably JS (publishes to) -> Ably Flutter

keep up the great work!
