### ISSUE TITLE
Android application got crash on notification receive in killed state using Ably notifications

### ISSUE THREAD

**Issue by Asharulislam** [ably/ably-flutter#429]
I am not using firebase_messaging package.

2022-06-15 16:34:16.617 26304-26365/com.appiskey.dang.dev E/AndroidRuntime: FATAL EXCEPTION: pool-12-thread-1
    Process: com.appiskey.dang.dev, PID: 26304
    java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-12-thread-1
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1280)
        at io.flutter.embedding.engine.FlutterJNI.setPlatformMessageHandler(FlutterJNI.java:854)
        at io.flutter.embedding.engine.dart.DartExecutor.onAttachedToJNI(DartExecutor.java:87)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:296)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:262)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:242)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:162)
        at io.ably.flutter.plugin.push.ManualFlutterApplicationRunner.<init>(ManualFlutterApplicationRunner.java:52)
        at io.ably.flutter.plugin.push.FirebaseMessagingReceiver.sendMessageToFlutterApplication(FirebaseMessagingReceiver.java:68)
        at io.ably.flutter.plugin.push.FirebaseMessagingReceiver.lambda$onReceive$0$FirebaseMessagingReceiver(FirebaseMessagingReceiver.java:36)
        at io.ably.flutter.plugin.push.-$$Lambda$FirebaseMessagingReceiver$Q7xqX52FAypmyYY-RYC6oZwb4P8.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2050) by [Unito](https://www.unito.io)

**Comment by Asharulislam** [comment]
I am not using firebase_messaging package.

**Comment by QuintinWillison** [comment]
@Asharulislam has this issue been created in response to https://github.com/ably/ably-flutter/issues/226#issuecomment-1142063300?

**Comment by Asharulislam** [comment]
@QuintinWillison (#266) comment is when I am using Flutter firebase messaging plugin and ably plugin both simultaneously. Now I have remove the firebase package and using ably for both notification and chatting purpose but my android application got crash in terminated state.

**Comment by davyskiba** [comment]
@Asharulislam, what flutter the flutter are you using?
It looks like an issue with dispatching the call to the proper thread in the SDK.

**Comment by Asharulislam** [comment]
@davyskiba 
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (8 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

package:
 ably_flutter: ^1.2.12

**Comment by davyskiba** [comment]
@Asharulislam thanks, I'll try to reproduce it on my side

**Comment by Asharulislam** [comment]
Now I am using latest package of Ably 1.2.15.
Flutter version 2.5.3

@QuintinWillison @ikbalkaya

If I send notifications then in Android (in terminated state) Application got crash.

Steps to reproduce:
1) Fire 6 to 8 notifications when the app is killed.
2) Received 2 or 4 notifications and some are still pending.
3) Just open the App (not from tapping the notification) from apps menu.
4) App just got crashed.

Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: io.ably.flutter.plugin. Response ID: 0
W/FlutterJNI(13840): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: io.ably.flutter.plugin. Response ID: 0
E/AndroidRuntime(13840): FATAL EXCEPTION: main
E/AndroidRuntime(13840): Process: com.appiskey.dang.dev, PID: 13840
E/AndroidRuntime(13840): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(13840):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
E/AndroidRuntime(13840):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(13840):        at io.ably.flutter.plugin.AblyMethodCallHandler$MethodResultWrapper.lambda$success$0$AblyMethodCallHandler$MethodResultWrapper(AblyMethodCallHandler.java:133)
E/AndroidRuntime(13840):        at io.ably.flutter.plugin.-$$Lambda$AblyMethodCallHandler$MethodResultWrapper$mM2gyGmNB_FxOxEa-tdyQn04YRo.run(Unknown Source:4)
E/AndroidRuntime(13840):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(13840):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13840):        at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(13840):        at android.app.ActivityThread.main(ActivityThread.java:8506)
E/AndroidRuntime(13840):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13840):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(13840):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
