### ISSUE TITLE
loading LocalDevice hit Unhandled Exception

### ISSUE THREAD

**Issue by dennislean** [ably/ably-flutter#491]
#### Issue:
On iOS, unable to get the device ID and client ID from the LocalDevice object due to unhandled exception when loading LocalDevice info.

#### Error Message:
```
Unhandled Exception: type '_Map<Object?, Object?>' is not a subtype of type 'String' in type cast
```

Exception throw from:
https://github.com/ably/ably-flutter/blob/c4b8ed69d7dc9020b1c8ed947bec6e07266f49d2/example/lib/push_notifications/push_notification_service.dart#L111

Actual problem from:
https://github.com/ably/ably-flutter/blob/c4b8ed69d7dc9020b1c8ed947bec6e07266f49d2/lib/src/platform/src/codec.dart#L799

#### More details:

This problem only happen on iOS due to the `recipient` contains object in the value.
```json
{
    "state": null,
    "errorReason": null,
    "recipient": {
        "transportType": "apns",
        "apnsDeviceTokens": {
            "default": "xxxxxxxxxxxxx"
        }
    }
}
```

However, It is working fine on Android because the `recipient` is a simple `Map<String, String>`.
```json
{
    "recipient": {
        "transportType": "fcm",
        "registrationToken": "xxxxxxx:xxxxxxx"
    }
}
```

#### Other Info:
Flutter: 3.13.5
Device: iPhone 11 (physical device), iOS 16.6.1
Editor: VS Code
Sample code: Ably example code from latest master branch (commit: c4b8ed69)

**Comment by dennislean** [comment]
Exception trace:
```dart
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type '_Map<Object?, Object?>' is not a subtype of type 'String' in type cast
#0      new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187:26)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#2      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186:11)
#3      Codec._decodeDevicePushDetails (package:ably_flutter/src/platform/src/codec.dart:799:33)
#4      Codec._decodeDeviceDetails (package:ably_flutter/src/platform/src/codec.dart:783:13)
#5      Codec._decodeLocalDevice (package:ably_flutter/src/platform/src/codec.dart:809:24)
#6      _CodecPair.decode (package:ably_flutter/src/platform/src/codec.dart:51:21)
#7      Codec.readValueOfType (package:ably_flutter/src/platform/src/codec.dart:230:19)
#8      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478:12)
#9      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:645:27)
#10     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#11     Platform.invokePlatformMethod (package:ably_flutter/src/platform/src/platform.dart:52:14)
<asynchronous suspension>
#12     PlatformObject.invokeRequest (package:ably_flutter/src/platform/src/platform_object.dart:74:22)
<asynchronous suspension>
#13     PushNotificationService.getDevice (package:ably_flutter_example/push_notifications/push_notification_service.dart:111:27)
<asynchronous suspension>
```
