### ISSUE TITLE
Error on Android Build

### ISSUE THREAD

**Issue by LaBolaCuba** [ably/ably-flutter#551]
Hi, i'm using ably with Flutter, on iOS is working fine but when i build for android this happend:

```
E/flutter (21393): <asynchronous suspension>
E/flutter (21393): #1      Platform.invokePlatformMethod (package:ably_flutter/src/platform/src/platform.dart:52:14)
E/flutter (21393): <asynchronous suspension>
E/flutter (21393): #2      Realtime.createPlatformInstance (package:ably_flutter/src/platform/src/realtime/realtime.dart:35:9)
E/flutter (21393): <asynchronous suspension>
E/flutter (21393): #3      PlatformObject._acquireHandle.<anonymous closure> (package:ably_flutter/src/platform/src/platform_object.dart:39:37)
E/flutter (21393): <asynchronous suspension>
E/flutter (21393): #4      PlatformObject._acquireHandle.<anonymous closure> (package:ably_flutter/src/platform/src/platform_object.dart:39:37)
E/flutter (21393): <asynchronous suspension>
E/flutter (21393): 
E/flutter (21393): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method createRealtime on channel io.ably.flutter.plugin)
E/flutter (21393): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (21393): <asynchronous suspension>
E/flutter (21393): #1      Platform.invokePlatformMethod (package:ably_flutter/src/platform/src/platform.dart:52:14)
E/flutter (21393): <asynchronous suspension>
E/flutter (21393): #2      Realtime.createPlatformInstance (package:ably_flutter/src/platform/src/realtime/realtime.dart:35:9)
E/flutter (21393): <asynchronous suspension>
E/flutter (21393): #3      PlatformObject._acquireHandle.<anonymous closure> (package:ably_flutter/src/platform/src/platform_object.dart:39:37)
E/flutter (21393): <asynchronous suspension>
E/flutter (21393): #4      PlatformObject._acquireHandle.<anonymous closure> (package:ably_flutter/src/platform/src/platform_object.dart:39:37)
E/flutter (21393): <asynchronous suspension>
E/flutter (21393): 
```

How i can solve this?, i'm going creazy with this. Ably on android don't work at all.

Env:
```
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (3 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 13.2.1 22D68 darwin-x64, locale es-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.94.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by LaBolaCuba** [comment]
> Hey @LaBolaCuba,
> 
> Could you please double-check that you’re trying to run the Flutter app on an Android emulator? Also, we’ve released `1.2.35`, which fixes another bug with the Android build for Flutter 3.24+

Hi @ttypic i only work with real devices. The error is on any android device i run. I test with 5 diferent android phones and see the error on all of them. PluginException.
